---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://mekrwagpgdfsba:61cf57e88fe90eed0750a846dd39a4199587f3739ff6f179401391cc1518a85e@ec2-3-213-41-172.compute-1.amazonaws.com:5432/d9p87asdojj97t
      DATABASE_TYPE: postgresql
      HASH_SALT: sxubdk34hg7-iwb76ysssa-dsgh7
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
